"""Generate the picker and database allowlist from Unicode emoji-test.txt."""
from pathlib import Path
import json, re, sys
source = Path(sys.argv[1]).read_text()
version = re.search(r'^# Version: (.+)$', source, re.M).group(1)
group = ''
rows = []
accepted = []
for line in source.splitlines():
    if line.startswith('# group: '):
        group = line.removeprefix('# group: ')
    match = re.match(r'^([0-9A-F ]+)\s*;\s*(fully-qualified|minimally-qualified|unqualified)\s*#\s*\S+\s+E[\d.]+\s+(.+)$', line)
    if not match:
        continue
    emoji = ''.join(chr(int(cp, 16)) for cp in match.group(1).split())
    label = match.group(3)
    accepted.append([emoji, label])
    if match.group(2) == 'fully-qualified':
        rows.append([emoji, label, group])
Path('src/data/emojis.json').write_text(json.dumps({'version': version, 'emojis': rows}, ensure_ascii=False, separators=(',', ':')) + '\n')
Path('src/data/emoji-variants.json').write_text(json.dumps(accepted, ensure_ascii=False, separators=(',', ':')) + '\n')
def sql_string(text):
    return "'" + text.replace("'", "''") + "'"
header = f'''-- Unicode Emoji {version}. Generated by scripts/generate-emoji-catalog.py.
-- Source: https://www.unicode.org/Public/emoji/latest/emoji-test.txt
create table public.emoji_catalog (emoji text primary key, label text not null);
alter table public.emoji_catalog enable row level security;
revoke all on public.emoji_catalog from anon, authenticated;
grant select on public.emoji_catalog to anon, authenticated;
create policy "Read emoji catalog" on public.emoji_catalog for select to anon, authenticated using (true);
'''
values = ',\n'.join('(' + sql_string(e) + ',' + sql_string(label) + ')' for e, label in accepted)
Path('supabase/migrations/202609170002_emoji_catalog.sql').write_text(header + '\ninsert into public.emoji_catalog(emoji,label) values\n' + values + ';\n\nalter table public.entries drop constraint if exists entries_emoji_check;\nalter table public.entries add constraint entries_emoji_catalog_fkey foreign key (emoji) references public.emoji_catalog(emoji);\n')
print(json.dumps({'unicode_version': version, 'picker_emojis': len(rows), 'accepted_sequences': len(accepted), 'categories': len(set(row[2] for row in rows))}))
