"""Build a repeatable SQL-editor setup for fresh or earlier MoodGrid databases."""
from pathlib import Path

checks = {
    "202609180001": "to_regclass('public.encrypted_vaults') is null",
    "202609160001": "to_regclass('public.entries') is null",
    "202609160002": "to_regclass('public.summary_rate_limits') is null",
    "202609170001": "to_regclass('public.profiles') is null",
    "202609170002": "to_regclass('public.emoji_catalog') is null",
    "202609170003": "to_regclass('public.stickers') is null",
    "202609170004": "not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Read own MoodGrid stickers')",
}
output = ["-- Generated by scripts/generate-setup.py. Run in the Supabase SQL editor.\n-- Works with a fresh database or earlier MoodGrid migrations; preserves existing data.\n-- All changes and backfills commit together. Safe to rerun after successful setup.\nbegin;\nselect pg_advisory_xact_lock(hashtext('moodgrid_setup'));\n"]
for path in sorted(Path("supabase/migrations").glob("*.sql")):
    version = path.name.split("_")[0]
    sql = path.read_text()
    delimiter = f"$migration_{version}$"
    output.append(f"-- {path.name}\ndo $setup$\nbegin\n  if {checks[version]} then\n    execute {delimiter}\n{sql}\n{delimiter};\n  end if;\nend;\n$setup$;\n")
output.append("notify pgrst, 'reload schema';\ncommit;\n")
Path("supabase/setup.sql").write_text("\n".join(output))
